version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 9.a, < 10"
  - dependency-name: vimeo/psalm
    versions:
    - 4.5.1
    - 4.6.1
    - 4.6.2
    - 4.6.4
  - dependency-name: symfony/console
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/event-dispatcher
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/routing
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/process
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: christophwurst/nextcloud
    versions:
    - 20.0.7
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@nextcloud/vue"
    versions:
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.8.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.10
    - 7.13.13
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@nextcloud/browserslist-config"
    versions:
    - 2.0.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
  - dependency-name: stylelint-scss
    versions:
    - 3.19.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
